version: '3.8'

services:
  px4:
    build:
      context: .
      dockerfile: Dockerfile.mac
      args:
        - ROS_VERSION=${ROS_VERSION}
        - PX4_VERSION=${PX4_VERSION}
    image: px4-mac:noetic
    container_name: ros-vnc
    volumes:
      - ../ws_fsm:/ws
    ports:
      - 6080:80
    shm_size: 512m
    tty: true
    stdin_open: true
    command: /bin/bash