version: '3.8'

services:
  px4:
    build:
      context: .
      dockerfile: Dockerfile.mac
    image: px4-mac:noetic
    container_name: ros-vnc
    volumes:
      - ..:/workspace
    ports:
      - 6080:80
      - "14570:14570/udp"
    shm_size: 512m
    tty: true
    stdin_open: true
    command: /bin/bash